import { AllProductProps } from "@/types/product.type";

export const menus = [
  {
    label: "About Us",
    link: "#about_us",
  },
  {
    label: "Our Strength",
    link: "#our_strength",
  },
  {
    label: "Products",
    link: "/products",
  },
  {
    label: "Galleries",
    link: "#galleries",
  },
  {
    label: "Production & Testing Equipment",
    link: "#production_testing",
    hide: true,
  },
  {
    label: "Download Catalog",
    link: undefined,
  },
];

export const galleries = ["image-gallery-1.png", "image-gallery-2.png"];

export const products: AllProductProps[] = [
  {
    name: "Mass Flow Meter MT-03",
    description:
      "The liquid turbine flow meter in the series LWGY are specially designed for usage in water, diesel, gas.",
    modelNo: "MT-03",
    nominalDiameter: "3mm",
    maxFlowRate: "360kg/h",
    liquidAccuracy: "±0.1%,+0.15%, ±0.2% , ±0.5%",
    tempAccuracy: "±1°C ±0.5% of reading",
    densityAccuracy: "±0.002g/cm3",
    zeroStability: "0.012kg/h",
    repeatability: "0.05%, 0.075%, 0.1%, 0.25%",
    mwp: "4MPa",
    operatingVoltage: "85-265VAC or 12-24VDC",
    ingressProtection: "IP65 / IP67",
    fluidTemp: "-10-+ 1 so°C. -200-+so°C. -40-+3oo°C",
    operatingTemp: "-3o-+so°Ct-4 o-+6o°C",
    vibratingTube: "Stainless steel 316L",
    endConnection: "DN15 Flange",
    commOutput: "RS485, Pulse, 4-20mA & HART",
    exMark: "Gii 2G Ex db IIC T6 ... T1 Gb",
    warranty: "2-year",
    certificate: "ATEX, IECEx, SIL,CE",
    packageSize: "515*305*235mm",
    gw: "15.2kgs",
    highlight: true,
    remark:
      "The above parameters are for our standard models. Please contact our sales team if you have any special requirement.",
    image: "product-image-mt-03.png",
    highlightLanding: true,
  },
  {
    name: "Mass Flow Meter MT-04",
    description:
      "The liquid turbine flow meter in the series LWGY are specially designed for usage in water, diesel, gas.",
    modelNo: "MT-04",
    nominalDiameter: "3mm",
    maxFlowRate: "360kg/h",
    liquidAccuracy: "±0.1%,+0.15%, ±0.2% , ±0.5%",
    tempAccuracy: "±1°C ±0.5% of reading",
    densityAccuracy: "±0.002g/cm3",
    zeroStability: "0.012kg/h",
    repeatability: "0.05%, 0.075%, 0.1%, 0.25%",
    mwp: "4MPa",
    operatingVoltage: "85-265VAC or 12-24VDC",
    ingressProtection: "IP65 / IP67",
    fluidTemp: "-10-+ 1 so°C. -200-+so°C. -40-+3oo°C",
    operatingTemp: "-3o-+so°Ct-4 o-+6o°C",
    vibratingTube: "Stainless steel 316L",
    endConnection: "DN15 Flange",
    commOutput: "RS485, Pulse, 4-20mA & HART",
    exMark: "Gii 2G Ex db IIC T6 ... T1 Gb",
    warranty: "2-year",
    certificate: "ATEX, IECEx, SIL,CE",
    packageSize: "515*305*235mm",
    gw: "15.2kgs",
    highlight: true,
    remark:
      "The above parameters are for our standard models. Please contact our sales team if you have any special requirement.",
    image: "product-image-mt-04.png",
    highlightLanding: true,
  },
  {
    name: "Mass Flow Meter MT-05",
    description:
      "The liquid turbine flow meter in the series LWGY are specially designed for usage in water, diesel, gas.",
    modelNo: "MT-05",
    nominalDiameter: "3mm",
    maxFlowRate: "360kg/h",
    liquidAccuracy: "±0.1%,+0.15%, ±0.2% , ±0.5%",
    tempAccuracy: "±1°C ±0.5% of reading",
    densityAccuracy: "±0.002g/cm3",
    zeroStability: "0.012kg/h",
    repeatability: "0.05%, 0.075%, 0.1%, 0.25%",
    mwp: "4MPa",
    operatingVoltage: "85-265VAC or 12-24VDC",
    ingressProtection: "IP65 / IP67",
    fluidTemp: "-10-+ 1 so°C. -200-+so°C. -40-+3oo°C",
    operatingTemp: "-3o-+so°Ct-4 o-+6o°C",
    vibratingTube: "Stainless steel 316L",
    endConnection: "DN15 Flange",
    commOutput: "RS485, Pulse, 4-20mA & HART",
    exMark: "Gii 2G Ex db IIC T6 ... T1 Gb",
    warranty: "2-year",
    certificate: "ATEX, IECEx, SIL,CE",
    packageSize: "515*305*235mm",
    gw: "15.2kgs",
    highlight: true,
    remark:
      "The above parameters are for our standard models. Please contact our sales team if you have any special requirement.",
    image: "product-image-mt-04.png",
    highlightLanding: true,
  },
  {
    name: "Mass Flow Meter MT-06",
    description:
      "The liquid turbine flow meter in the series LWGY are specially designed for usage in water, diesel, gas.",
    modelNo: "MT-06",
    nominalDiameter: "3mm",
    maxFlowRate: "360kg/h",
    liquidAccuracy: "±0.1%,+0.15%, ±0.2% , ±0.5%",
    tempAccuracy: "±1°C ±0.5% of reading",
    densityAccuracy: "±0.002g/cm3",
    zeroStability: "0.012kg/h",
    repeatability: "0.05%, 0.075%, 0.1%, 0.25%",
    mwp: "4MPa",
    operatingVoltage: "85-265VAC or 12-24VDC",
    ingressProtection: "IP65 / IP67",
    fluidTemp: "-10-+ 1 so°C. -200-+so°C. -40-+3oo°C",
    operatingTemp: "-3o-+so°Ct-4 o-+6o°C",
    vibratingTube: "Stainless steel 316L",
    endConnection: "DN15 Flange",
    commOutput: "RS485, Pulse, 4-20mA & HART",
    exMark: "Gii 2G Ex db IIC T6 ... T1 Gb",
    warranty: "2-year",
    certificate: "ATEX, IECEx, SIL,CE",
    packageSize: "515*305*235mm",
    gw: "15.2kgs",
    highlight: true,
    remark:
      "The above parameters are for our standard models. Please contact our sales team if you have any special requirement.",
    image: "product-image-mt-06.png",
  },
  {
    name: "Mass Flow Meter MT-07",
    description:
      "The liquid turbine flow meter in the series LWGY are specially designed for usage in water, diesel, gas.",
    modelNo: "MT-07",
    nominalDiameter: "3mm",
    maxFlowRate: "360kg/h",
    liquidAccuracy: "±0.1%,+0.15%, ±0.2% , ±0.5%",
    tempAccuracy: "±1°C ±0.5% of reading",
    densityAccuracy: "±0.002g/cm3",
    zeroStability: "0.012kg/h",
    repeatability: "0.05%, 0.075%, 0.1%, 0.25%",
    mwp: "4MPa",
    operatingVoltage: "85-265VAC or 12-24VDC",
    ingressProtection: "IP65 / IP67",
    fluidTemp: "-10-+ 1 so°C. -200-+so°C. -40-+3oo°C",
    operatingTemp: "-3o-+so°Ct-4 o-+6o°C",
    vibratingTube: "Stainless steel 316L",
    endConnection: "DN15 Flange",
    commOutput: "RS485, Pulse, 4-20mA & HART",
    exMark: "Gii 2G Ex db IIC T6 ... T1 Gb",
    warranty: "2-year",
    certificate: "ATEX, IECEx, SIL,CE",
    packageSize: "515*305*235mm",
    gw: "15.2kgs",
    highlight: true,
    remark:
      "The above parameters are for our standard models. Please contact our sales team if you have any special requirement.",
    image: "product-image-mt-07.png",
  },
  {
    name: "Mass Flow Meter MT-08",
    description:
      "The liquid turbine flow meter in the series LWGY are specially designed for usage in water, diesel, gas.",
    modelNo: "MT-08",
    nominalDiameter: "3mm",
    maxFlowRate: "360kg/h",
    liquidAccuracy: "±0.1%,+0.15%, ±0.2% , ±0.5%",
    tempAccuracy: "±1°C ±0.5% of reading",
    densityAccuracy: "±0.002g/cm3",
    zeroStability: "0.012kg/h",
    repeatability: "0.05%, 0.075%, 0.1%, 0.25%",
    mwp: "4MPa",
    operatingVoltage: "85-265VAC or 12-24VDC",
    ingressProtection: "IP65 / IP67",
    fluidTemp: "-10-+ 1 so°C. -200-+so°C. -40-+3oo°C",
    operatingTemp: "-3o-+so°Ct-4 o-+6o°C",
    vibratingTube: "Stainless steel 316L",
    endConnection: "DN15 Flange",
    commOutput: "RS485, Pulse, 4-20mA & HART",
    exMark: "Gii 2G Ex db IIC T6 ... T1 Gb",
    warranty: "2-year",
    certificate: "ATEX, IECEx, SIL,CE",
    packageSize: "515*305*235mm",
    gw: "15.2kgs",
    remark:
      "The above parameters are for our standard models. Please contact our sales team if you have any special requirement.",
    image: "product-image-mt-08.png",
  },
];
